title: Ash Theme
description: "A minimalistic Jekyll theme priotizing calm, simplicity, and elegance. Made by Rohan."
encoding: utf-8

# Profile image settings
# Uncomment and update these lines to show a profile image
profile_image: /assets/images/flowers.png
profile_image_alt: "Author profile picture"

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]